#!/usr/bin/env ruby
require 'optparse'
require_relative '../lib/mchat/version.rb'
require_relative "../lib/mchat/timeline"


OptionParser.new do |opts|
  opts.banner = "Usage: mchat [options]"

  opts.on("--version", "version") do
    
    puts "MchatTimeline v#{::Mchat::VERSION}"
    puts ""
    puts "author: mark24"
    puts "mail: mark.zhangyoung@qq.com"
    return
  end
end.parse!

tl = Mchat::Timeline.new

trap("INT") { tl.hook_close }

tl.run
